title: SPORA 
author: 
  name: "Roberto Dell'Orco"
  email: roorco@gmail.com 
metadata:
  description: 'SPORA, association loi 1901, rassemble un collectif multidisciplinaire dont les recherches-actions portent sur la culture des champignons dans la ville.'

